package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

func addCompletionCommand(rootCmd *cobra.Command) {
	completionCmd := &cobra.Command{
		Use:                   "completion [bash|zsh|fish|powershell|csh|tcsh]",
		Short:                 "Output shell completion script",
		Hidden:                true,
		DisableFlagsInUseLine: true,
		Args:                  cobra.ExactArgs(1),
		ValidArgs:             []string{"bash", "zsh", "fish", "powershell", "csh", "tcsh"},
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCompletion(rootCmd, cmd.OutOrStdout(), args[0])
		},
	}

	rootCmd.AddCommand(completionCmd)
}

func runCompletion(rootCmd *cobra.Command, out io.Writer, shell string) error {
	switch strings.ToLower(strings.TrimSpace(shell)) {
	case "bash":
		return rootCmd.GenBashCompletionV2(out, true)
	case "zsh":
		return rootCmd.GenZshCompletion(out)
	case "fish":
		return rootCmd.GenFishCompletion(out, true)
	case "powershell":
		return rootCmd.GenPowerShellCompletionWithDesc(out)
	case "csh", "tcsh":
		_, err := io.WriteString(out, buildCShellCompletion(rootCmd))
		return err
	default:
		return fmt.Errorf("unsupported shell %q", shell)
	}
}

func buildCShellCompletion(rootCmd *cobra.Command) string {
	rootName := rootCmd.Name()
	topLevel := visibleCommandNames(rootCmd.Commands())

	lines := make([]string, 0, 4)
	lines = append(lines,
		"# csh/tcsh completion for "+rootName,
		"# Generated by `"+rootName+" completion tcsh`.",
	)
	if len(topLevel) > 0 {
		lines = append(lines, fmt.Sprintf("complete %s 'p/1/(%s)/'", rootName, strings.Join(topLevel, " ")))
	}

	for _, name := range topLevel {
		sub := rootCmd.Commands()
		var child *cobra.Command
		for _, candidate := range sub {
			if candidate.Name() == name {
				child = candidate
				break
			}
		}
		if child == nil {
			continue
		}
		subCommands := visibleCommandNames(child.Commands())
		if len(subCommands) == 0 {
			continue
		}
		lines = append(lines, fmt.Sprintf("complete %s 'n/%s/p/2/(%s)/'", rootName, name, strings.Join(subCommands, " ")))
	}

	return strings.Join(lines, "\n") + "\n"
}

func visibleCommandNames(commands []*cobra.Command) []string {
	names := make([]string, 0, len(commands))
	for _, cmd := range commands {
		if cmd.Hidden {
			continue
		}
		if cmd.Name() == "help" {
			continue
		}
		names = append(names, cmd.Name())
	}
	sort.Strings(names)
	return names
}
